version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: qyin-env
      IMAGE_TAG: latest
      # set Docker Hub username & password in CircleCI
      # DOCKER_USERNAME
      # DOCKER_PASSWORD
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      # use stdin prevents the password from ending up in the shell's history or log-files.
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10
