version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      environment:
        IMAGE_NAME: qyin-env
        IMAGE_TAG: 2020
        # set Docker Hub username & password in CircleCI
        # DOCKER_USERNAME
        # DOCKER_PASSWORD

      steps:
        - checkout

        - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
        - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10
